'use client';
import './globals.scss';
import './styles/style.scss';
import { Provider } from 'react-redux';
import store from './redux/store';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './components/header';
import Footer from './components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <Provider store={store}>{children}</Provider>
        <Footer></Footer>
      </body>
    </html>
  );
}
